spring:
  application:
    name: coffee-shop-server

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: ${FLYWAY_ENABLED:false}

  profiles:
    active:
      - service
      - local
    group:
      ddl:
        - local

  jackson:
    deserialization:
      use-big-decimal-for-floats: true
    generator:
      write-numbers-as-strings: false
      write-bigdecimal-as-plain: true

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET}

server:
  port: ${PORT:8080}
