# Android app properties
targetSdk=36
minSdk=30
versionCode=1

# TODO Change user-facing application name (also used in JavaDoc generation).
appName=My Project

# TODO Change version number as appropriate.
version=1.0.0

# OpenAPI client generation properties
openApiSpecification=../server/src/main/openapi/openapi.yaml
openApiOutputDirectory=generated/openapi
openApiGeneratorName=kotlin
openApiLibrary=jvm-retrofit2
openApiApiPackage=edu.cnm.deepdive.coffeeshop.service.openapi
openApiModelPackage=edu.cnm.deepdive.coffeeshop.model.dto.openapi
openApiModelNameSuffix=Dto
openApiSerializationLibrary=moshi
openApiUseCoroutines=true
openApiDateLibrary=java8
